### ISSUE TITLE
Handle multiple email addresses for a user

### ISSUE THREAD

**Issue by pat** [rubyaustralia/ruby_au#130]
Many folks sign up for conferences and camps using a mixture of work and personal email addresses, and so they get invitations for joining Ruby Australia as a member more than once.

It'd be nice if we could allow people to associate multiple email addresses with their membership. We'd want to confirm each email address, and then modify the invitation system so it's smart enough to skip over people if _any_ of their email addresses are in the system.

It'd also be good to allow people, upon getting an extra invite, to have a one-click solution for associating that email address with their existing account (I'm guessing: link in email, which prompts a sign-in, which then allows people to click a button to confirm the association).

**Comment by gamesover** [comment]
The library [devise-multi_email](https://github.com/allenwq/devise-multi_email) is a great tool for handling this task. Once users have multiple email addresses, we need to address the following considerations:

- Enabling login with multiple email addresses.
- Sending confirmations to all associated email addresses.
- Allowing password recovery using any of the email addresses.
- Implementing validations for multiple email addresses.

Additionally, we should follow the steps outlined in [Migrating existing user records](https://github.com/allenwq/devise-multi_email/wiki/Migrating-existing-user-records).

For now, I propose that we continue sending emails only to the user’s primary email address. This approach aligns with our current email-sending logic. In the future, we can enhance the logic to include sending emails to all associated addresses for a user.

Regarding this suggestion:
> It'd also be good to allow people, upon getting an extra invite, to have a one-click solution for associating that email address with their existing account (I'm guessing: link in email, which prompts a sign-in, which then allows people to click a button to confirm the association).

This could be handled as a separate ticket for implementation later.

**Comment by gamesover** [comment]
You're absolutely right, @quintrino . From my personal experience, the most common scenario is that each account is tied to a single email address, with employees typically registering using their staff or company email. When they leave the company, their account is usually disabled. If they still wish to use the website, they typically need to register with a personal email address. I haven't encountered the situations you described before. However, I believe the issue could be resolved by allowing users to associate multiple email addresses with their account, but ensuring that only one email is active and usable for login at any given time.

As we discussed on Slack, I will start by linking the account to multiple email addresses. The remaining logic or extensions can be adjusted based on this foundation.

**Comment by leesheppard** [comment]
This issue can now be closed with thanks to @gamesover for putting in the time to help implement this for the community.
