### ISSUE TITLE
Cancellation of membership

### ISSUE THREAD

**Issue by evolve2k** [rubyaustralia/ruby_au#196]
Hi folks, I thought recently I hadnt heard much from Ruby Austalia, and then realsied I wasnt officially a member, so signed up.
That all went great!

Accessing my account I saw there is a "Cancel your account" button or similar (cant remember the exact name).
I clicked it as I was curious in what you folks might show next, often sites have a little "Sorrt to see you go, what was the issue, this is what happens next.. sorta thing.. and I was curious to see what might be there").

It triggered an immediate cancellation, and a little embarassed I sheapishly reached out to @pat after attempting to just sign up again and getting "Email address is taken" error.

Pat pointed me to the login page.. where I found the "Reactivate your account" link.
A little embarassed I've then set about reactivating my account, which had it's own issue.

**The request in this Issue is to update the UI**

**Easy fix:** Add a label to the button like "Pressing this button will immediatley process your cancellation"

**Nicer fix:** Button goes to a new page /sorry-you-are-leaving and a short exit interview is asked, maybe a dropdown list of reason for leaving and a space to write in a text box, maybe sends an email to the committee or such.

Also, once cancelled, seems no email is sent.. and the UI just reports a notice.. would be good if that notice includes.. to reactivate go to "sign in" > "Reactivate.." giving me clues as to how to sign back up.

**Comment by gamesover** [comment]
I don't know whether I've found the right position.
I did find a link [Resign from Ruby Australia](http://localhost:3000/my/membership) in http://localhost:3000/my/details URL

However, when I clicked it, it looks like the `Easy fix` version had already been implemented 5 years ago. Since it asked double confirm to cancel the account.

![image](https://github.com/user-attachments/assets/6b7bffb3-bd8b-41ed-995c-ed17af0ccb33)

@quintrino please correct me if I've made a mistake. Thank you

**Comment by Cueball** [comment]
Confirming that the current site implementation does show a JS confirmation dialog:
![image](https://github.com/user-attachments/assets/c449e3e8-487f-4f85-8b85-15f9f9213af4)

Curious to know what might happen if JS was disabled - would that prevent the resignation, or proceed without showing a confirmation? [I wasn't game to try that on the live site…]

**Comment by gamesover** [comment]
@Cueball Thank you for confirming. I believe JavaScript has become fundamental to all web pages today.

I'm curious to know whether you or the other maintainers of Ruby AU still consider this request valid. I'm contemplating whether we should close it or enhance it.

**Comment by quintrino** [comment]
I think the main focus of this ticket is to prevent unintentional cancellation. It sounds like this pop up resolves that. I am happy for this ticket to be marked as closed.
