### ISSUE TITLE
A member with admin rights can switch a profile from public to private, or delete a profile altogether

### ISSUE THREAD

**Issue by antulik** [rubyaustralia/ruby_au#41]
Admins need to be able to remove problematic content from public view quickly and easily by switching public profiles to private.

Admins also need to be able to remove a member altogether, if their membership has been revoked, or at the request of the member.

**Comment by Cueball** [comment]
Closing as Stale; AFAICT we don't have intentions to provide Ruby AU user profiles (issue predates current version of Ruby AU website)
