### ISSUE TITLE
Do we need separate account for SendGrid?

### ISSUE THREAD

**Issue by antulik** [rubyaustralia/ruby_au#55]
Right now SendGrid account added as a heroku plugin. Do we need to create a separate account and then link it to the app rather than use the provided one. 

Personally I prefer to keep separate accounts so it's easier to reuse them. Thoughts?

**Comment by pat** [comment]
Given we're not paying for Sendgrid on either the association or conference sites, I'm fine with them being separate accounts (and I'm not sure we're sending any emails at all from the conference site). Certainly, if we had to pay, and it was cheaper to use a single paid account than two paid add-ons, we could look at changing, but I'm not expecting that to be something we need in the near future.
