### ISSUE TITLE
Fix Lachlan's Bio Pic

### ISSUE THREAD

**Issue by JasonDataIO** [rubyaustralia/ruby_au#64]
Found a little issue with a bio pic from the website.  Lachlan's image was not showing up even though he had a photo in the appropriate image folder.

<img width="759" alt="screen shot 2018-02-06 at 8 12 03 pm" src="https://user-images.githubusercontent.com/25572606/35850811-273e14a8-0b7a-11e8-9645-819d523afd7d.png">

It's may be because proper image fingerprinting is not taking place for precompiled assets that are `jpeg` and not `jpg`.  Inspecting the Lachlan's image source showed that a fingerprint was not appended to the file name.  Perhaps, converting the file name can fix the problem?

https://github.com/rails/sprockets-rails/issues/304

**Comment by pat** [comment]
A much delayed response to  this (I wasn't tracking the repo back then) - but Lachlan's photo is now fixed (and he's displayed on the previous committee page, rather than the current). Thanks for noting the issue!
